[script:buttercup_storefront_ip_profile]
match = /buttercup/storefront/ip_profile
script = storefront_api.py
handler = storefront_api.StorefrontAPIHandler
scripttype = persist
python.version = python3
requireAuthentication = true
capability.post = search
output_modes = json
passPayload = true
passSession = true

[script:buttercup_storefront_sessions]
match = /buttercup/storefront/sessions
script = storefront_api.py
handler = storefront_api.StorefrontAPIHandler
scripttype = persist
python.version = python3
requireAuthentication = true
capability.post = search
output_modes = json
passPayload = true
passSession = true
