[script:buttercup_security_rank_ssh_attackers]
match = /buttercup/security/rank_ssh_attackers
script = security_api.py
handler = security_api.SecurityAPIHandler
scripttype = persist
python.version = python3
requireAuthentication = true
capability.post = search
output_modes = json
passPayload = true
passSession = true

[script:buttercup_security_ssh_source_profile]
match = /buttercup/security/ssh_source_profile
script = security_api.py
handler = security_api.SecurityAPIHandler
scripttype = persist
python.version = python3
requireAuthentication = true
capability.post = search
output_modes = json
passPayload = true
passSession = true

[script:buttercup_security_ssh_source_targets]
match = /buttercup/security/ssh_source_targets
script = security_api.py
handler = security_api.SecurityAPIHandler
scripttype = persist
python.version = python3
requireAuthentication = true
capability.post = search
output_modes = json
passPayload = true
passSession = true
